name: Remote Host
on: [workflow_dispatch]

jobs:
  run-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Start Engine
        run: |
          node server.js & 
          sleep 10
          npx cloudflared tunnel --url http://127.0.0.1:8080 &
          sleep 21600
