name: Remote Host
on: [workflow_dispatch]

jobs:
  run-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install
        run: npm install

      - name: Start
        run: |
          node server.js & 
          npx cloudflared tunnel --url http://localhost:8080
